name: Release

on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/misc/release_notes.md
          generate_release_notes: true

  pypi-release:
    strategy:
      matrix:
        python-version: ['3.x']
        poetry-version: ['1.5.1']
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry==${{ matrix.poetry-version }}
        # Use pipx if the workflow becomes complex
        # https://python-poetry.org/docs/master#ci-recommendations
      - name: Build and publish to PyPI
        run: poetry publish --build
